// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: replication.proto

#include "replication.pb.h"
#include "replication.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

static const char* ReplicationService_method_names[] = {
  "/ReplicationService/Configure",
  "/ReplicationService/Put",
  "/ReplicationService/Get",
  "/ReplicationService/Ack",
  "/ReplicationService/VersionQuery",
};

std::unique_ptr< ReplicationService::Stub> ReplicationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ReplicationService::Stub> stub(new ReplicationService::Stub(channel, options));
  return stub;
}

ReplicationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Configure_(ReplicationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Put_(ReplicationService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(ReplicationService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Ack_(ReplicationService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_VersionQuery_(ReplicationService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ReplicationService::Stub::Configure(::grpc::ClientContext* context, const ::NodeConfig& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NodeConfig, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Configure_, context, request, response);
}

void ReplicationService::Stub::async::Configure(::grpc::ClientContext* context, const ::NodeConfig* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NodeConfig, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Configure_, context, request, response, std::move(f));
}

void ReplicationService::Stub::async::Configure(::grpc::ClientContext* context, const ::NodeConfig* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Configure_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ReplicationService::Stub::PrepareAsyncConfigureRaw(::grpc::ClientContext* context, const ::NodeConfig& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::NodeConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Configure_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ReplicationService::Stub::AsyncConfigureRaw(::grpc::ClientContext* context, const ::NodeConfig& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConfigureRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ReplicationService::Stub::Put(::grpc::ClientContext* context, const ::PutRequest& request, ::PutResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::PutRequest, ::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Put_, context, request, response);
}

void ReplicationService::Stub::async::Put(::grpc::ClientContext* context, const ::PutRequest* request, ::PutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::PutRequest, ::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void ReplicationService::Stub::async::Put(::grpc::ClientContext* context, const ::PutRequest* request, ::PutResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::PutResponse>* ReplicationService::Stub::PrepareAsyncPutRaw(::grpc::ClientContext* context, const ::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::PutResponse, ::PutRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Put_, context, request);
}

::grpc::ClientAsyncResponseReader< ::PutResponse>* ReplicationService::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::PutRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPutRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ReplicationService::Stub::Get(::grpc::ClientContext* context, const ::GetRequest& request, ::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GetRequest, ::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void ReplicationService::Stub::async::Get(::grpc::ClientContext* context, const ::GetRequest* request, ::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GetRequest, ::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void ReplicationService::Stub::async::Get(::grpc::ClientContext* context, const ::GetRequest* request, ::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GetResponse>* ReplicationService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GetResponse, ::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GetResponse>* ReplicationService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ReplicationService::Stub::Ack(::grpc::ClientContext* context, const ::AckRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AckRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ack_, context, request, response);
}

void ReplicationService::Stub::async::Ack(::grpc::ClientContext* context, const ::AckRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AckRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ack_, context, request, response, std::move(f));
}

void ReplicationService::Stub::async::Ack(::grpc::ClientContext* context, const ::AckRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ack_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ReplicationService::Stub::PrepareAsyncAckRaw(::grpc::ClientContext* context, const ::AckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::AckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ack_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* ReplicationService::Stub::AsyncAckRaw(::grpc::ClientContext* context, const ::AckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ReplicationService::Stub::VersionQuery(::grpc::ClientContext* context, const ::VersionQueryRequest& request, ::VersionQueryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::VersionQueryRequest, ::VersionQueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_VersionQuery_, context, request, response);
}

void ReplicationService::Stub::async::VersionQuery(::grpc::ClientContext* context, const ::VersionQueryRequest* request, ::VersionQueryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::VersionQueryRequest, ::VersionQueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VersionQuery_, context, request, response, std::move(f));
}

void ReplicationService::Stub::async::VersionQuery(::grpc::ClientContext* context, const ::VersionQueryRequest* request, ::VersionQueryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VersionQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::VersionQueryResponse>* ReplicationService::Stub::PrepareAsyncVersionQueryRaw(::grpc::ClientContext* context, const ::VersionQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::VersionQueryResponse, ::VersionQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_VersionQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::VersionQueryResponse>* ReplicationService::Stub::AsyncVersionQueryRaw(::grpc::ClientContext* context, const ::VersionQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVersionQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

ReplicationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ReplicationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ReplicationService::Service, ::NodeConfig, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ReplicationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NodeConfig* req,
             ::google::protobuf::Empty* resp) {
               return service->Configure(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ReplicationService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ReplicationService::Service, ::PutRequest, ::PutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ReplicationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::PutRequest* req,
             ::PutResponse* resp) {
               return service->Put(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ReplicationService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ReplicationService::Service, ::GetRequest, ::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ReplicationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GetRequest* req,
             ::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ReplicationService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ReplicationService::Service, ::AckRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ReplicationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AckRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->Ack(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ReplicationService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ReplicationService::Service, ::VersionQueryRequest, ::VersionQueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ReplicationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::VersionQueryRequest* req,
             ::VersionQueryResponse* resp) {
               return service->VersionQuery(ctx, req, resp);
             }, this)));
}

ReplicationService::Service::~Service() {
}

::grpc::Status ReplicationService::Service::Configure(::grpc::ServerContext* context, const ::NodeConfig* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ReplicationService::Service::Put(::grpc::ServerContext* context, const ::PutRequest* request, ::PutResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ReplicationService::Service::Get(::grpc::ServerContext* context, const ::GetRequest* request, ::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ReplicationService::Service::Ack(::grpc::ServerContext* context, const ::AckRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ReplicationService::Service::VersionQuery(::grpc::ServerContext* context, const ::VersionQueryRequest* request, ::VersionQueryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


